config/routes.rb
Rails.application.routes.draw do
  resources :incidents do
    collection do
      get :detailed_report
      post 'detailed_report' => 'incidents#detailed_report_create'
      get :thank_you
    end
  end
  root 'incidents#simple_report'
  post '/' => 'incidents#simple_report_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incident.rb
class Incident < ApplicationRecord

  enum incident_type: %w[Alcohol Assault Bullying Hazing Drugs Graffiti Injury Suspicious\ Activity Trespassing Vandalism Weapons\ Violation Technology\ Misuse Other]
  enum role: %w[Student Teacher Other\ Staff Parent Community\ Member]

  # associations
  has_many :incident_files, dependent: :destroy

  # validations
  validates :description, presence: true

  accepts_nested_attributes_for :incident_files
end

app/models/incident_file.rb
class IncidentFile < ApplicationRecord
  has_attached_file :attachment
  
  # associations
  belongs_to :incident

  # validations
  do_not_validate_attachment_file_type :attachment # allow all types files as attachment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:simple_report, :detailed_report]

  # POST /
  def simple_report_create
    create_report :simple_report
  end


  # POST /incidents/detailed_report
  def detailed_report_create
    create_report :detailed_report
  end

  # GET /incidents/thank_you
  def thank_you
    redirect_to root_path unless request.referrer.present?
  end

  private
    def set_incident
      @incident = Incident.new
      @incident.incident_files.build
    end

    def create_report source
      @incident = Incident.new(incident_params)

      if @incident.save
        redirect_to thank_you_incidents_path
      else
        render source
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:school, :description, :incident_type, :name, :email, :phone, :role, :people_involved, :other_observers, :incident_datetime, :location, incident_files_attributes: [:id, :attachment, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
  def predefined_locations
    [
      'On school campuses and grounds',
      'During transportation to and from school', 
      'At school-sponsored events',
      'More details'
    ]
  end

  def get_collection enum_attribute
    enum_attribute.keys.map { |key| [key.humanize, key] }
  end
end

app/views/incidents/detailed_report.html.erb
<div class='pb-2 mt-4 mb-2 border-bottom'>
  <p class='font-weight-bold mb-0'>Submit Detailed Report</p>
</div>

<%= nested_form_for(@incident, url: detailed_report_incidents_path) do |form| %>
  <%= render 'shared/form_errors', object: form.object %>

  <div class='form-group'>
    <%= form.label :incident_type %>
    <%= form.select :incident_type, options_for_select(get_collection(Incident.incident_types)), {}, {class: 'form-control'} %>
  </div>

  <div class='form-group'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :role %>
    <%= form.select :role, options_for_select(get_collection(Incident.roles)), {}, {class: 'form-control'} %>
  </div>

  <div class='form-group'>
    <%= form.label :people_involved %>
    <%= form.text_area :people_involved, class: 'form-control', placeholder: 'Name and other details of people involved (student, teacher, staff, parent, grade level)' %>
  </div>

  <div class='form-group'>
    <%= form.label :other_observers %>
    <%= form.text_area :other_observers, class: 'form-control', placeholder: 'Name and details' %>
  </div>

  <div class='form-group'>
    <%= form.label :incident_datetime %>
    <%= form.datetime_select :incident_datetime, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :location %>
    <%= form.select :location, options_for_select(predefined_locations), {}, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label 'Describe issue/incident' %>*
    <%= form.text_area :description, class: 'form-control', required: true %>
  </div>

  <%= form.fields_for :incident_files do |inc_file_form| %>
    <div class='form-group'>
      <%= link_to 'Add Attachment', 'javascript:void(0)', class: 'btn btn-secondary add-incident-photo' %>
      <%= inc_file_form.file_field :attachment, class: 'd-none' %>
      <%= inc_file_form.link_to_remove 'Remove' %>
    </div>
  <% end %>
  <p><%= form.link_to_add 'Add', :incident_files %></p>

  <div class='form-group'>
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    initIncidents();
  })
</script>

app/views/incidents/simple_report.html.erb
<div class='pb-2 mt-4 mb-2 border-bottom'>
  <p class='font-weight-bold mb-0'>Lincoln High School</p>
  <p class='font-weight-light mb-0'>Incident Reporting Page</p>
</div>

<%= nested_form_for(@incident, url: root_path) do |form| %>
  <%= render 'shared/form_errors', object: form.object %>

  <%= form.hidden_field :school, value: 'Lincoln High School', class: 'form-control' %>

  <div class='form-group'>
    <%= form.label 'Describe issue/incident' %>*
    <%= form.text_area :description, class: 'form-control', required: true %>
  </div>

  <%= form.fields_for :incident_files do |inc_file_form| %>
    <div class='form-group'>
      <%= link_to 'Add Photos', 'javascript:void(0)', class: 'btn btn-secondary add-incident-photo' %>
      <%= inc_file_form.file_field :attachment, class: 'd-none' %>
      <%= inc_file_form.link_to_remove 'Remove' %>
    </div>
  <% end %>
  <p><%= form.link_to_add 'Add', :incident_files %></p>

  <div class='form-group'>
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

<%= link_to 'Or Submit Detailed Report', detailed_report_incidents_path %>

<script>
  $(document).ready(function() {
    initIncidents();
  })
</script>

app/views/incidents/thank_you.html.erb
<div class="pb-2 mt-4 alert alert-success" role="alert">
  <strong>Thank You!</strong> We have received incident report.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncidentReporting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">Error</h4>
    <p><%= pluralize(object.errors.count, "error") %> prohibited this form being saved:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>